/**
 * Runtime export.
 * Hard-cut public surface: vault core plus explicit clients only.
 */

export { IdentityError, IdentityErrorCode } from "../errors.js";
export { derivePublicKey, LocalSigner } from "../protocol/crypto.js";
export { deriveIdentityId } from "../protocol/identity.js";
export type { IStorageProvider } from "../storage/provider.js";
export { FsStorageProvider } from "../storage/fs.js";
export { MemoryStorageProvider } from "../storage/memory.js";
export {
  createIdentity,
  restoreIdentity,
  type CreateIdentityOptions,
  type RestoreIdentityOptions,
  type CreatedIdentity,
} from "./identity.js";
export {
  createVault,
  recoverVault,
  type CreateVaultOptions,
  type CreatedVault,
  type RecoverVaultOptions,
  type RecoveredVault,
} from "./bootstrap.js";

export {
  createVaultCore,
  DefaultVaultCore,
  VaultCoreError,
  createDefaultVaultCoreDependencies,
  type CreateDefaultVaultCoreDependenciesOptions,
  type DefaultPolicyEngineOptions,
  DefaultPolicyEngine,
  createPersistentVaultCoreDependencies,
  initializeVaultCustody,
  recoverVaultWorkingKey,
  DEFAULT_VAULT_KEY_CUSTODY_BLOB_KEY,
  type InitializeVaultCustodyOptions,
  type InitializedVaultCustody,
  type CreatePersistentVaultCoreDependenciesOptions,
  PersistentVaultAuditLog,
  PersistentVaultCapabilityRegistry,
  PersistentVaultCapabilityRevocationRegistry,
  PersistentVaultCustomHttpFlowRegistry,
  PersistentVaultRateLimitStore,
  PersistentVaultReplayGuard,
  PersistentVaultSecretCustody,
  PersistentVaultSecretRepository,
  HttpDispatchExecutor,
  InMemoryAgentIdentityRegistry,
  InMemoryCapabilityRegistry,
  InMemoryCapabilityRevocationRegistry,
  InMemoryCustomHttpFlowRegistry,
  InMemoryRateLimitStore,
  InMemoryReplayGuard,
  InMemoryAuditLog,
  InMemoryOwnerIdentityRegistry,
  InMemorySecretCustody,
  InMemorySecretRepository,
  RandomIdGenerator,
  SignatureOwnerProofVerifier,
  type SignatureAgentProofVerifierOptions,
  SignatureAgentProofVerifier,
  SystemClock,
  type AgentCapability,
  type AgentIdentityRecord,
  type AgentProof,
  type OwnerAuditRequest,
  type OwnerExportSecretRequest,
  type OwnerRegisterCapabilityCommand,
  type OwnerRegisterAgentIdentityCommand,
  type OwnerRegisterCustomHttpFlowCommand,
  type OwnerSecretExport,
  type OwnerIdentityRecord,
  type CustomHttpFlowDefinition,
  type OwnerProof,
  type AuditEntry,
  type AuditLog,
  type AuditQuery,
  type Clock,
  type DispatchAuthorization,
  type DispatchInstruction,
  type DispatchRequest,
  type DispatchResult,
  type IdGenerator,
  type OwnerIdentityRegistry,
  type OwnerProofVerifier,
  type PolicyEngine,
  type RateLimitStore,
  type ReplayGuard,
  type CustomHttpFlowRegistry,
  type SecretAlias,
  type SecretCustody,
  type SecretId,
  type SecretRecord,
  type SecretRepository,
  type SecretVersion,
  type TrustedExecutor,
  type VaultCore,
  type VaultCoreDependencies,
  type VaultPrincipal,
  type VaultPrincipalKind,
  type VaultTargetBinding,
  type VaultWriteSecretCommand,
  type VaultId,
  type AgentIdentityRegistry,
  type AgentProofVerifier,
  type CapabilityRevocationRegistry,
  type CapabilityRegistry,
} from "../vault-core/index.js";

export {
  createVaultClient,
  type VaultClient,
  type VaultIdentity,
  type VaultSigner,
  type VaultAuditQueryInput,
  type VaultExportSecretInput,
  type VaultGrantCapabilityInput,
  type VaultRegisterFlowInput,
  type VaultRegisterAgentInput,
  type OwnerSecretTargetBinding,
  type OwnerWriteSecretInput,
} from "../clients/owner/index.js";

export {
  createAgentClient,
  type AgentClient,
  type AgentIdentity,
  type AgentCapabilityEnvelope,
  type AgentDispatchIntent,
  type AgentDispatchTransport,
  type AgentSigner,
} from "../clients/agent/index.js";

export {
  createVaultService,
  wrapVaultCoreAsVaultService,
  createOwnerHttpFlowBoundary,
  createStandardAcquireBoundary,
  createStandardDispatchBoundary,
  toOwnerHttpFlowBoundary,
  type VaultService,
  type VaultAcquireSecretInput,
  type VaultAcquireSecretResult,
  type VaultAcquireSecretFlow,
  type VaultCustomFlowResolver,
  type VaultAgentDispatchRequest,
  type VaultAgentDispatchResponse,
  type VaultAgentDispatchErrorResponse,
  type RedactedResponseShape,
  type OwnerHttpFlowBoundary,
} from "../vault-ingress/index.js";

export {
  LocalVaultTransport,
} from "../vault-ingress/defaults.js";
