export { createOwnerClient } from "./client.js";

export type {
  OwnerClient,
  CreateOwnerClientOptions,
  OwnerAgentProvisionResult,
  OwnerCreateSecretInput,
  OwnerUpdateSecretInput,
  OwnerRemoveSecretInput,
  VaultAuditQueryInput,
  VaultExportSecretInput,
  VaultReadSecretPlaintextInput,
  VaultReadAgentPrivateKeyInput,

  VaultImportAgentInput,
  VaultCreateAgentInput,
  VaultUpdateAgentInput,
  VaultRemoveAgentInput,
  VaultListAgentsInput,
  VaultListRequestsInput,
  VaultGetRequestInput,
  VaultListSecretsInput,
  VaultIssueSessionTokenInput,
  VaultRevokeSessionTokenInput,
  OwnerSensitiveActionConfirmation,
  OwnerSensitiveActionContext,
  VaultGrantAgentSecretInput,
  VaultGrantSecretDestinationInput,
  VaultRevokeAgentSecretInput,
  VaultRevokeSecretDestinationInput,
  VaultListGrantsInput,
  VaultApproveDispatchInput,
} from "./contracts.js";
