export { createVaultCore, DefaultVaultCore } from "./core.js";
export { VaultCoreError } from "./errors.js";
export {
  createDefaultVaultCoreDependencies,
  type CreateDefaultVaultCoreDependenciesOptions,
  type DefaultPolicyEngineOptions,
  DefaultPolicyEngine,
  HttpDispatchExecutor,
  InMemoryAgentIdentityRegistry,
  InMemoryCapabilityRegistry,
  InMemoryCapabilityRevocationRegistry,
  InMemoryCustomHttpFlowRegistry,
  InMemoryRateLimitStore,
  InMemoryReplayGuard,
  InMemoryAuditLog,
  InMemoryOwnerIdentityRegistry,
  InMemorySecretCustody,
  InMemorySecretRepository,
  RandomIdGenerator,
  SignatureOwnerProofVerifier,
  type SignatureAgentProofVerifierOptions,
  SignatureAgentProofVerifier,
  SystemClock,
} from "./defaults.js";
export {
  createPersistentVaultCoreDependencies,
  initializeVaultCustody,
  recoverVaultWorkingKey,
  DEFAULT_VAULT_KEY_CUSTODY_BLOB_KEY,
  FileAgentIdentityRegistry as PersistentVaultAgentIdentityRegistry,
  FileAuditLog as PersistentVaultAuditLog,
  FileOwnerIdentityRegistry as PersistentVaultOwnerIdentityRegistry,
  FileCapabilityRegistry as PersistentVaultCapabilityRegistry,
  FileCapabilityRevocationRegistry as PersistentVaultCapabilityRevocationRegistry,
  FileCustomHttpFlowRegistry as PersistentVaultCustomHttpFlowRegistry,
  FileRateLimitStore as PersistentVaultRateLimitStore,
  FileReplayGuard as PersistentVaultReplayGuard,
  FileSecretCustody as PersistentVaultSecretCustody,
  FileSecretRepository as PersistentVaultSecretRepository,
} from "./persistence.js";

export type {
  InitializeVaultCustodyOptions,
  InitializedVaultCustody,
  CreatePersistentVaultCoreDependenciesOptions,
} from "./persistence.js";

export type {
  AgentCapability,
  AgentIdentityRecord,
  AgentProof,
  OwnerAuditRequest,
  OwnerExportSecretRequest,
  OwnerDefineSecretTargetsCommand,
  OwnerRegisterCapabilityCommand,
  OwnerRegisterAgentIdentityCommand,
  OwnerRegisterCustomHttpFlowCommand,
  OwnerSecretExport,
  OwnerIdentityRecord,
  CustomHttpFlowDefinition,
  OwnerProof,
  AuditEntry,
  AuditQuery,
  DispatchAuthorization,
  DispatchInstruction,
  DispatchRequest,
  DispatchResult,
  IssuerWriteSecretCommand,
  OwnerWriteSecretCommand,
  SecretAlias,
  SecretId,
  SecretRecord,
  SecretVersion,
  VaultPrincipal,
  VaultPrincipalKind,
  VaultTargetBinding,
  VaultWriteSecretCommand,
  VaultId,
} from "./contracts.js";

export type {
  AgentIdentityRegistry,
  AgentProofVerifier,
  AuditLog,
  CapabilityRegistry,
  Clock,
  IdGenerator,
  OwnerIdentityRegistry,
  OwnerProofVerifier,
  PolicyEngine,
  RateLimitStore,
  ReplayGuard,
  CustomHttpFlowRegistry,
  SecretRepository,
  SecretCustody,
  TrustedExecutor,
  VaultCore,
  VaultCoreDependencies,
  CapabilityRevocationRegistry,
} from "./ports.js";
