export { createVaultCore, VaultCore } from "./core.js";
export { VaultCoreError, type VaultCoreErrorCode } from "./errors.js";
export {
  createVaultCoreDependencies,
  type VaultCoreDependenciesOptions,
  type DefaultPolicyEngineOptions,
  DefaultPolicyEngine,
  HttpDispatchExecutor,
  InMemoryAgentIdentityRegistry,
  InMemoryAgentSecretGrantRegistry,
  InMemorySecretDestinationGrantRegistry,

  InMemoryAuditLog,
  InMemorySessionTokenRegistry,
  InMemorySecretCustody,
  InMemorySecretRepository,
  InMemoryRequestRecordRegistry,
  InMemoryReplayGuard,
  RandomIdGenerator,
  type SignatureAgentProofVerifierOptions,
  SignatureAgentProofVerifier,
  SystemClock,
} from "./defaults.js";
export {
  createPersistentVaultCoreDependencies,
  initializeVaultCustody,
  recoverVaultWorkingKey,
  DEFAULT_VAULT_KEY_CUSTODY_BLOB_KEY,
  FileAgentIdentityRegistry as PersistentVaultAgentIdentityRegistry,
  FileAuditLog as PersistentVaultAuditLog,
  FileAgentSecretGrantRegistry as PersistentVaultAgentSecretGrantRegistry,
  FileSecretDestinationGrantRegistry as PersistentVaultSecretDestinationGrantRegistry,

  FileSecretCustody as PersistentVaultSecretCustody,
  FileSecretRepository as PersistentVaultSecretRepository,
} from "./persistence.js";

export type {
  InitializeVaultCustodyOptions,
  InitializedVaultCustody,
  CreatePersistentVaultCoreDependenciesOptions,
} from "./persistence.js";

export type {
  AgentId,
  AgentSecretGrant,
  SecretDestinationGrant,
  GrantStatus,
  AgentIdentityRecord,
  AgentSelfContext,
  AgentProof,
  AgentVisibleSecretRecord,
  AgentListGrantsRequest,
  AgentListSecretsRequest,
  AgentGetRuntimeManifestRequest,
  AgentGetRuntimeManifestCommand,
  AgentRuntimeManifest,
  AgentListRequestsRequest,
  AgentGetRequestRequest,
  AgentVisibleRequestRecord,
  AgentRequestRecord,
  OwnerVisibleRequestRecord,
  OwnerRequestRecord,
  AgentRequestResult,
  OwnerAuditRequest,
  OwnerDeleteSecretCommand,
  OwnerCreateSecretCommand,
  OwnerExportSecretRequest,
  OwnerListAgentsRequest,
  OwnerListRequestsRequest,
  OwnerGetRequestRequest,
  OwnerRegisterAgentIdentityCommand,
  OwnerUpdateAgentIdentityCommand,

  OwnerIssueSessionTokenRequest,
  OwnerSessionToken,
  OwnerSecretExport,
  OwnerGrantAgentSecretCommand,
  OwnerGrantSecretDestinationCommand,
  OwnerRevokeAgentSecretCommand,
  OwnerRevokeSecretDestinationCommand,
  OwnerListGrantsRequest,
  OwnerApproveDispatchCommand,
  DispatchApprovalDecision,

  AuditEntry,
  AuditQuery,
  DispatchAuthorization,
  DispatchInstruction,
  DispatchRequest,
  DispatchResult,
  RequestRecord,
  IssuerWriteSecretCommand,
  OwnerUpdateSecretCommand,
  SecretAlias,
  SecretId,
  SecretLifecycleStatus,
  SecretRecord,
  SecretSource,
  SecretSourceInput,
  SecretVersion,
  VaultPrincipal,
  VaultPrincipalKind,
  VaultWriteSecretCommand,
  VaultId,
} from "./contracts.js";

export {
  DispatchStatus,
  AuditOperation,
} from "./contracts.js";

export type {
  AgentIdentityRegistry,
  AgentProofVerifier,
  AuditLog,
  AgentSecretGrantRegistry,
  SecretDestinationGrantRegistry,
  Clock,
  IdGenerator,
  PolicyEngine,

  SecretRepository,
  SecretCustody,
  TrustedExecutor,
  VaultCoreDependencies,
} from "./ports.js";
